# action.yaml
name: 'HCAP Github Action'
description: 'HCAP Github Action'
author: Juned Memon(junaid18183)

inputs:
  url:
    description: HCAP URL
    required: true
  username:
    description: HCAP username
    required: true
  password:
    description: HCAP password
    required: true

outputs:
  hcap_version:
    description: 'hcap_version'

runs:
  using: docker
  image: image/Dockerfile
  entrypoint: /action.sh

branding:
  icon: globe
  color: purple
